packages:
  - example
  - website

nodeLinker: hoisted
linkWorkspacePackages: true
minimumReleaseAge: 1440
allowBuilds:
  core-js: false
  esbuild: false
  unrs-resolver: false
patchedDependencies:
  react-native@0.88.0-rc.1: patches/react-native@0.88.0-rc.1.patch
